<?php

return [
    'default_department' => 'engineering',

    'status_groups' => [
        'draft' => ['draft'],
        'open' => ['submitted', 'pending', 'approved', 'in_progress'],
        'closed' => ['completed', 'rejected', 'cancelled'],
    ],

    'workflows' => [
        'warehouse_request' => [
            'label' => 'Warehouse Request Flow',
            'initial_status' => 'draft',
            'terminal_statuses' => ['completed', 'rejected', 'cancelled'],
            'statuses' => [
                'draft' => 'Draft',
                'pending' => 'Pending Approval',
                'approved' => 'Approved',
                'in_progress' => 'Fulfillment',
                'completed' => 'Completed',
                'rejected' => 'Rejected',
                'cancelled' => 'Cancelled',
            ],
            'transitions' => [
                'draft' => ['pending', 'cancelled'],
                'pending' => ['approved', 'rejected', 'cancelled'],
                'approved' => ['in_progress', 'completed', 'cancelled'],
                'in_progress' => ['completed', 'cancelled'],
                'completed' => [],
                'rejected' => [],
                'cancelled' => [],
            ],
        ],
        'standard_request' => [
            'label' => 'Standard Service Request Flow',
            'initial_status' => 'draft',
            'terminal_statuses' => ['completed', 'rejected', 'cancelled'],
            'statuses' => [
                'draft' => 'Draft',
                'submitted' => 'Submitted',
                'approved' => 'Approved',
                'in_progress' => 'In Progress',
                'completed' => 'Completed',
                'rejected' => 'Rejected',
                'cancelled' => 'Cancelled',
            ],
            'transitions' => [
                'draft' => ['submitted', 'cancelled'],
                'submitted' => ['approved', 'rejected', 'cancelled'],
                'approved' => ['in_progress', 'completed', 'cancelled'],
                'in_progress' => ['completed', 'cancelled'],
                'completed' => [],
                'rejected' => [],
                'cancelled' => [],
            ],
        ],
        'work_order' => [
            'label' => 'Engineering Work Order Flow',
            'initial_status' => 'draft',
            'terminal_statuses' => ['completed', 'rejected', 'cancelled'],
            'statuses' => [
                'draft' => 'Draft',
                'submitted' => 'Submitted',
                'approved' => 'Approved',
                'open' => 'Open',
                'progress' => 'In Progress',
                'closed' => 'Closed',
                'completed' => 'Completed',
                'rejected' => 'Rejected',
                'cancelled' => 'Cancelled',
            ],
            'transitions' => [
                'draft' => ['submitted', 'cancelled'],
                'submitted' => ['approved', 'rejected', 'cancelled'],
                'approved' => ['open', 'progress', 'closed', 'completed'],
                'open' => ['progress', 'closed'],
                'progress' => ['closed'],
                'closed' => ['completed'],
                'completed' => [],
                'rejected' => [],
                'cancelled' => [],
            ],
        ],
    ],

    'department_aliases' => [
        'eng' => 'engineering',
        'engineering' => 'engineering',
        'it' => 'it',
        'ga' => 'ga',
        'general_affair' => 'ga',
        'general_affairs' => 'ga',
        'warehouse' => 'warehouse',
    ],

    'departments' => [
        'engineering' => [
            'label' => 'Department Engineering',
            'catalog_label' => 'Engineering services',
            'services' => [
                [
                    'key' => 'engineering_warehouse',
                    'name' => 'Warehouse',
                    'description' => 'Permintaan barang, fulfillment gudang utama, stock area, dan pengeluaran area.',
                    'icon' => 'fa-boxes-stacked',
                    'status' => 'Aktif',
                    'requesting_department' => 'engineering',
                    'owner_department' => 'warehouse',
                    'workflow' => 'warehouse_request',
                    'request_types' => [
                        [
                            'key' => 'material_request',
                            'label' => 'Permintaan Barang',
                            'description' => 'Request barang dari gudang utama.',
                            'legacy_module' => 'trBPB',
                            'route' => 'transaksi.index',
                        ],
                        [
                            'key' => 'area_receiving',
                            'label' => 'Terima dari Gudang',
                            'description' => 'Penerimaan barang dari gudang utama ke stock area.',
                            'legacy_module' => 'warehouse2_receiving',
                            'route' => 'warehouse2.receiving.index',
                        ],
                        [
                            'key' => 'area_issuing',
                            'label' => 'Pengeluaran Area',
                            'description' => 'Pengeluaran barang dari stock area.',
                            'legacy_module' => 'warehouse2_issuing',
                            'route' => 'warehouse2.issuing.index',
                        ],
                    ],
                    'route' => 'dashboard',
                    'enabled' => true,
                    'generic_enabled' => false,
                    'roles' => ['admin', 'user', 'approval', 'approval_level1', 'approval2'],
                    'actions' => [
                        [
                            'label' => 'Ajukan PB',
                            'route' => 'transaksi.index',
                            'roles' => ['admin', 'user', 'approval', 'approval_level1', 'approval2'],
                        ],
                        [
                            'label' => 'Area Stock',
                            'route' => 'warehouse2.stock.index',
                            'roles' => ['admin', 'user'],
                        ],
                        [
                            'label' => 'PB Fulfillment',
                            'route' => 'warehouse.pb.index',
                            'roles' => ['admin', 'user'],
                            'departments' => ['warehouse'],
                        ],
                        [
                            'label' => 'Approval PB',
                            'route' => 'transaksi.index',
                            'roles' => ['admin', 'approval', 'approval_level1', 'approval2'],
                        ],
                    ],
                ],
                [
                    'key' => 'it_request',
                    'name' => 'IT Request',
                    'description' => 'Akun, perangkat, software, jaringan, dan support IT.',
                    'icon' => 'fa-laptop-code',
                    'status' => 'Aktif',
                    'requesting_department' => 'engineering',
                    'owner_department' => 'it',
                    'workflow' => 'standard_request',
                    'request_types' => [
                        [
                            'key' => 'account_access',
                            'label' => 'Account & Access',
                            'description' => 'Akun, reset akses, email, dan permission aplikasi.',
                            'legacy_module' => null,
                            'route' => null,
                        ],
                        [
                            'key' => 'device_support',
                            'label' => 'Device Support',
                            'description' => 'Laptop, printer, scanner, dan perangkat kerja.',
                            'legacy_module' => null,
                            'route' => null,
                        ],
                        [
                            'key' => 'network_support',
                            'label' => 'Network Support',
                            'description' => 'Internet, Wi-Fi, LAN, dan koneksi sistem.',
                            'legacy_module' => null,
                            'route' => null,
                        ],
                    ],
                    'route' => 'e-requests.create',
                    'query' => ['service_key' => 'it_request'],
                    'enabled' => true,
                    'generic_enabled' => true,
                    'roles' => ['admin', 'user'],
                    'actions' => [
                        [
                            'label' => 'Buat IT Request',
                            'route' => 'e-requests.create',
                            'query' => ['service_key' => 'it_request'],
                            'roles' => ['admin', 'user'],
                        ],
                    ],
                ],
                [
                    'key' => 'ga_request',
                    'name' => 'GA Request',
                    'description' => 'Fasilitas, kendaraan, ATK, cleaning, dan support umum.',
                    'icon' => 'fa-building-user',
                    'status' => 'Aktif',
                    'requesting_department' => 'engineering',
                    'owner_department' => 'ga',
                    'workflow' => 'standard_request',
                    'request_types' => [
                        [
                            'key' => 'facility_request',
                            'label' => 'Facility Request',
                            'description' => 'Perbaikan fasilitas, ruangan, lampu, AC, dan utilitas umum.',
                            'legacy_module' => null,
                            'route' => null,
                        ],
                        [
                            'key' => 'vehicle_request',
                            'label' => 'Vehicle Request',
                            'description' => 'Kebutuhan kendaraan operasional.',
                            'legacy_module' => null,
                            'route' => null,
                        ],
                        [
                            'key' => 'office_supply',
                            'label' => 'Office Supply',
                            'description' => 'ATK dan kebutuhan support kantor.',
                            'legacy_module' => null,
                            'route' => null,
                        ],
                    ],
                    'route' => 'e-requests.create',
                    'query' => ['service_key' => 'ga_request'],
                    'enabled' => true,
                    'generic_enabled' => true,
                    'roles' => ['admin', 'user'],
                    'actions' => [
                        [
                            'label' => 'Buat GA Request',
                            'route' => 'e-requests.create',
                            'query' => ['service_key' => 'ga_request'],
                            'roles' => ['admin', 'user'],
                        ],
                    ],
                ],
                [
                    'key' => 'engineering_service',
                    'name' => 'Engineering',
                    'description' => 'Work order, maintenance request, dan perbaikan equipment.',
                    'icon' => 'fa-screwdriver-wrench',
                    'status' => 'Aktif',
                    'requesting_department' => 'engineering',
                    'owner_department' => 'engineering',
                    'workflow' => 'work_order',
                    'request_types' => [
                        [
                            'key' => 'work_order',
                            'label' => 'Work Order',
                            'description' => 'Request pekerjaan maintenance atau perbaikan equipment.',
                            'legacy_module' => 'trWorkOrder',
                            'route' => 'workorder.index',
                        ],
                    ],
                    'route' => 'e-requests.create',
                    'query' => ['service_key' => 'engineering_service', 'request_type_key' => 'work_order'],
                    'enabled' => true,
                    'generic_enabled' => false,
                    'roles' => ['admin', 'user', 'approval', 'approval_level1'],
                    'actions' => [
                        [
                            'label' => 'Work Order',
                            'route' => 'e-requests.create',
                            'query' => ['service_key' => 'engineering_service', 'request_type_key' => 'work_order'],
                            'roles' => ['admin', 'user', 'approval', 'approval_level1'],
                        ],
                    ],
                ],
            ],
        ],
        'it' => [
            'label' => 'Department IT',
            'catalog_label' => 'IT services',
            'services' => [],
        ],
        'ga' => [
            'label' => 'Department GA',
            'catalog_label' => 'GA services',
            'services' => [],
        ],
        'warehouse' => [
            'label' => 'Department Warehouse',
            'catalog_label' => 'Warehouse services',
            'services' => [],
        ],
    ],
];
