-- Engineering Apps stable schema snapshot before PB/WO backdate
-- Generated: 2026-07-20 11:40:50 Asia/Jakarta
-- Schema only, no ERP/app transaction data included.

-- Table: trBPB
CREATE TABLE `trBPB` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nomor_pb` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tanggal_permintaan` date NOT NULL,
  `bagian` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `untuk` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `untuk_id` bigint unsigned DEFAULT NULL COMMENT 'ID mesin atau bangunan',
  `reference_wo_id` bigint unsigned DEFAULT NULL,
  `reference_wo_number` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mesin_id` bigint unsigned DEFAULT NULL COMMENT 'ID mesin',
  `bangunan_id` bigint unsigned DEFAULT NULL COMMENT 'ID bangunan',
  `dari_gudang` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_diperlukan` date NOT NULL,
  `jenis_pekerjaan` enum('repair','maintenance','utility','project','overhaul') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'maintenance',
  `status` enum('pending','verification','approved','rejected','in_progress','completed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `approval_level_required` tinyint unsigned NOT NULL DEFAULT '1',
  `approval_current_level` tinyint unsigned NOT NULL DEFAULT '1',
  `has_high_value_item` tinyint(1) NOT NULL DEFAULT '0',
  `erp_gi_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `erp_gi_recorded_by` bigint unsigned DEFAULT NULL,
  `erp_gi_recorded_at` timestamp NULL DEFAULT NULL,
  `is_legacy` tinyint(1) NOT NULL DEFAULT '0',
  `legacy_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `legacy_at` timestamp NULL DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `approved_by` bigint unsigned DEFAULT NULL,
  `approval_level_1_at` timestamp NULL DEFAULT NULL,
  `approval_level_1_by` bigint unsigned DEFAULT NULL,
  `approval_level_2_at` timestamp NULL DEFAULT NULL,
  `approval_level_2_by` bigint unsigned DEFAULT NULL,
  `rejected_at` timestamp NULL DEFAULT NULL,
  `rejected_by` bigint unsigned DEFAULT NULL,
  `rejection_reason` text COLLATE utf8mb4_unicode_ci,
  `user_id` bigint unsigned NOT NULL,
  `verification_section_head_id` bigint unsigned DEFAULT NULL,
  `verification_status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'verified',
  `verified_by` bigint unsigned DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `verification_notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `keterangan` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `trbpb_nomor_pb_unique` (`nomor_pb`),
  KEY `trbpb_user_id_foreign` (`user_id`),
  CONSTRAINT `trbpb_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=93 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: trBPBDetail
CREATE TABLE `trBPBDetail` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `trBPB_id` bigint unsigned NOT NULL,
  `id_mesin` bigint unsigned DEFAULT NULL,
  `barang_id` bigint unsigned DEFAULT NULL,
  `nama_barang` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `material_type` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sparepart',
  `kode_barang` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipe_mesin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merk_mesin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jumlah` decimal(10,2) NOT NULL,
  `satuan` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `unit_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `total_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `is_high_value` tinyint(1) NOT NULL DEFAULT '0',
  `fulfillment_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `fulfillment_source` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fulfillment_note` text COLLATE utf8mb4_unicode_ci,
  `erp_gi_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `erp_gi_recorded_by` bigint unsigned DEFAULT NULL,
  `erp_gi_recorded_at` timestamp NULL DEFAULT NULL,
  `stock_area_doc_number` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stock_area_stock_id` bigint unsigned DEFAULT NULL,
  `fulfilled_by` bigint unsigned DEFAULT NULL,
  `fulfilled_at` timestamp NULL DEFAULT NULL,
  `keterangan` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `trbpbdetail_trbpb_id_foreign` (`trBPB_id`),
  CONSTRAINT `trbpbdetail_trbpb_id_foreign` FOREIGN KEY (`trBPB_id`) REFERENCES `trBPB` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=111 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: trWorkOrder
CREATE TABLE `trWorkOrder` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nomor` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `judul` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `deskripsi` text COLLATE utf8mb4_general_ci,
  `tanggal_pekerjaan` date DEFAULT NULL,
  `file_path` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `status` enum('draft','submitted','approved','rejected','completed') COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'draft',
  `progress_status` enum('open','progress','closed') COLLATE utf8mb4_general_ci DEFAULT NULL,
  `open_at` datetime DEFAULT NULL,
  `progress_at` datetime DEFAULT NULL,
  `closed_at` datetime DEFAULT NULL,
  `progress_notes` text COLLATE utf8mb4_general_ci,
  `assigned_regu` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `assigned_by` bigint unsigned DEFAULT NULL,
  `assigned_at` datetime DEFAULT NULL,
  `delegation_notes` text COLLATE utf8mb4_general_ci,
  `submitted_by` int DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `approved_by` int DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `rejected_by` int DEFAULT NULL,
  `rejected_at` datetime DEFAULT NULL,
  `rejection_notes` text COLLATE utf8mb4_general_ci,
  `completed_by` int DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `trWorkOrder_nomor_unique` (`nomor`),
  KEY `trWorkOrder_nomor_index` (`nomor`),
  KEY `trWorkOrder_status_index` (`status`),
  KEY `trWorkOrder_created_by_index` (`created_by`),
  CONSTRAINT `trWorkOrder_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: trWorkOrderPhotos
CREATE TABLE `trWorkOrderPhotos` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `work_order_id` bigint unsigned NOT NULL,
  `uploaded_by` bigint unsigned DEFAULT NULL,
  `file_path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `trworkorderphotos_work_order_id_index` (`work_order_id`),
  KEY `trworkorderphotos_uploaded_by_index` (`uploaded_by`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: mobile_api_tokens
CREATE TABLE `mobile_api_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `token_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `device_name` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcm_token` text COLLATE utf8mb4_unicode_ci,
  `fcm_registered_at` timestamp NULL DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mobile_api_tokens_token_hash_unique` (`token_hash`),
  KEY `mobile_api_tokens_user_id_index` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=549 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: historical_import_batches
CREATE TABLE `historical_import_batches` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `batch_number` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `original_file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stored_file_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `signoff_notes` text COLLATE utf8mb4_unicode_ci,
  `total_rows` int unsigned NOT NULL DEFAULT '0',
  `valid_rows` int unsigned NOT NULL DEFAULT '0',
  `invalid_rows` int unsigned NOT NULL DEFAULT '0',
  `total_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `uploaded_by` bigint unsigned NOT NULL,
  `uploaded_at` timestamp NULL DEFAULT NULL,
  `submitted_by` bigint unsigned DEFAULT NULL,
  `submitted_at` timestamp NULL DEFAULT NULL,
  `signed_off_by` bigint unsigned DEFAULT NULL,
  `signed_off_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `historical_import_batches_batch_number_unique` (`batch_number`),
  KEY `historical_import_batches_uploaded_by_foreign` (`uploaded_by`),
  KEY `historical_import_batches_submitted_by_foreign` (`submitted_by`),
  KEY `historical_import_batches_signed_off_by_foreign` (`signed_off_by`),
  CONSTRAINT `historical_import_batches_signed_off_by_foreign` FOREIGN KEY (`signed_off_by`) REFERENCES `users` (`id`),
  CONSTRAINT `historical_import_batches_submitted_by_foreign` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`id`),
  CONSTRAINT `historical_import_batches_uploaded_by_foreign` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: historical_import_rows
CREATE TABLE `historical_import_rows` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `batch_id` bigint unsigned NOT NULL,
  `row_number` int unsigned NOT NULL,
  `transaction_type` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `group_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requester_user_id` bigint unsigned DEFAULT NULL,
  `section_head_user_id` bigint unsigned DEFAULT NULL,
  `target_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_id` bigint unsigned DEFAULT NULL,
  `realization_date` date DEFAULT NULL,
  `gi_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gi_date` date DEFAULT NULL,
  `item_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qty` decimal(18,4) DEFAULT NULL,
  `unit` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit_price` decimal(18,2) DEFAULT NULL,
  `total_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `material_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `job_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `raw_payload` json DEFAULT NULL,
  `validation_errors` json DEFAULT NULL,
  `committed_record_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `committed_record_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `historical_import_rows_requester_user_id_foreign` (`requester_user_id`),
  KEY `historical_import_rows_section_head_user_id_foreign` (`section_head_user_id`),
  KEY `hist_rows_batch_type_idx` (`batch_id`,`transaction_type`),
  KEY `hist_rows_commit_idx` (`committed_record_type`,`committed_record_id`),
  CONSTRAINT `historical_import_rows_batch_id_foreign` FOREIGN KEY (`batch_id`) REFERENCES `historical_import_batches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `historical_import_rows_requester_user_id_foreign` FOREIGN KEY (`requester_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `historical_import_rows_section_head_user_id_foreign` FOREIGN KEY (`section_head_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: users
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'user',
  `department_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  UNIQUE KEY `users_username_unique` (`username`),
  KEY `users_department_code_index` (`department_code`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
